"""Production-grade Telegram bot worker with:
- async-safe Telegram handling
- async DB access via asyncio.to_thread (compatible with existing sync get_connection())
- durable Redis Streams queue for scalability
- graceful shutdown, lock file protection, rate limiting, retries, cleanup, and status updates

Required env vars:
- TELEGRAM_BOT_TOKEN
- REDIS_URL (e.g. redis://localhost:6379/0)

Optional env vars:
- BOT_MODE=bot | worker | both   (default: bot)
- TELEGRAM_RETRY_BASE_SECONDS=10
- TELEGRAM_RETRY_MAX_SECONDS=180
- MAX_VIDEO_SIZE_MB=300
- UPLOADS_DIR=/path/to/uploads
- LOCK_FILE=/tmp/gentstationai_bot_worker.lock
- QUEUE_STREAM=telegram:submissions
- QUEUE_GROUP=telegram-workers
- QUEUE_CONSUMER=<auto-generated>
- RATE_LIMIT_MAX_FILES=5
- RATE_LIMIT_WINDOW_SECONDS=60
- HEARTBEAT_INTERVAL_SECONDS=30
- DB_STATUS_KEY=telegram_bot_status

Dependencies:
- python-telegram-bot>=20
- redis>=5
- python-dotenv

This file assumes your existing `core.database.get_connection()` returns a synchronous DB connection.
"""

from __future__ import annotations

import asyncio
import atexit
import json
import logging
import os
import signal
import subprocess
import socket
import tempfile
import time
import uuid
from contextlib import suppress
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Any, Optional

from dotenv import load_dotenv
try:
    from redis.asyncio import Redis
except ImportError:
    Redis = None
from telegram import Update
from telegram.error import NetworkError, RetryAfter, TelegramError, TimedOut
from telegram.ext import Application, ApplicationBuilder, CommandHandler, ContextTypes, MessageHandler, filters

# Keep your existing DB layer.
from core.database import get_connection


# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(name)s: %(message)s")
logging.getLogger("httpx").setLevel(logging.WARNING)
logging.getLogger("telegram").setLevel(logging.WARNING)
logging.getLogger("urllib3").setLevel(logging.WARNING)
logger = logging.getLogger("bot_worker")


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
BOT_STATUS_KEY = os.getenv("DB_STATUS_KEY", "telegram_bot_status")
BOT_HEARTBEAT_INTERVAL = int(os.getenv("HEARTBEAT_INTERVAL_SECONDS", "30"))
RETRY_BASE_SECONDS = int(os.getenv("TELEGRAM_RETRY_BASE_SECONDS", "10"))
RETRY_MAX_SECONDS = int(os.getenv("TELEGRAM_RETRY_MAX_SECONDS", "180"))
MAX_VIDEO_SIZE_MB = int(os.getenv("MAX_VIDEO_SIZE_MB", "300"))
RATE_LIMIT_MAX_FILES = int(os.getenv("RATE_LIMIT_MAX_FILES", "5"))
RATE_LIMIT_WINDOW_SECONDS = int(os.getenv("RATE_LIMIT_WINDOW_SECONDS", "60"))
LOCK_FILE = Path(os.getenv("LOCK_FILE", "/tmp/gentstationai_bot_worker.lock"))
UPLOADS_DIR = Path(os.getenv("UPLOADS_DIR", str(Path(__file__).resolve().parents[1] / "uploads")))
QUEUE_STREAM = os.getenv("QUEUE_STREAM", "telegram:submissions")
QUEUE_GROUP = os.getenv("QUEUE_GROUP", "telegram-workers")
BOT_MODE = os.getenv("BOT_MODE", "bot").strip().lower()  # bot | worker | both
TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
PROJECT_ROOT = Path(__file__).resolve().parents[1]
ALLOWED_VIDEO_SUFFIXES = {".mp4", ".mov", ".mkv", ".webm"}
ALLOWED_MIME_PREFIXES = ("video/",)
ALLOWED_MIME_TYPES = {"video/mp4", "video/quicktime", "video/webm", "video/x-matroska"}


# ---------------------------------------------------------------------------
# Runtime state
# ---------------------------------------------------------------------------
shutdown_event = asyncio.Event()
bot_running_event = asyncio.Event()
rate_limit_state: dict[str, list[float]] = {}
rate_limit_lock = asyncio.Lock()
heartbeat_task: Optional[asyncio.Task] = None
cleanup_task: Optional[asyncio.Task] = None
redis_client: Optional[Redis] = None


# ---------------------------------------------------------------------------
# Data structures
# ---------------------------------------------------------------------------
@dataclass
class SubmissionJob:
    job_id: str
    chat_id: str
    employee_id: int
    station_id: int
    file_path: str
    original_file_name: str
    size_bytes: int
    created_ts: float

    def to_redis_mapping(self) -> dict[str, str]:
        d = asdict(self)
        return {k: str(v) for k, v in d.items()}

    @staticmethod
    def from_redis_mapping(mapping: dict[str, Any]) -> "SubmissionJob":
        def _get(key: str, default: Any = None) -> Any:
            v = mapping.get(key, default)
            if isinstance(v, bytes):
                return v.decode("utf-8")
            return v

        return SubmissionJob(
            job_id=str(_get("job_id")),
            chat_id=str(_get("chat_id")),
            employee_id=int(_get("employee_id")),
            station_id=int(_get("station_id")),
            file_path=str(_get("file_path")),
            original_file_name=str(_get("original_file_name", "")),
            size_bytes=int(_get("size_bytes", 0)),
            created_ts=float(_get("created_ts", time.time())),
        )


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
def _now() -> float:
    return time.time()


def _safe_json(value: Any) -> str:
    return json.dumps(value, separators=(",", ":"), ensure_ascii=False)


def _ps_alive(pid: int) -> bool:
    if pid <= 0:
        return False
    try:
        os.kill(pid, 0)
    except OSError:
        return False

    # Detect zombie processes via ps
    try:
        stat = subprocess.check_output(
            ["ps", "-p", str(pid), "-o", "stat="],
            text=True,
        ).strip()
        if not stat:
            return False
        if stat.upper().startswith("Z"):
            return False
    except Exception:
        pass

    return True


def acquire_lock() -> bool:
    """Create a stale-safe lock file to avoid duplicate bot/worker launches."""
    try:
        fd = os.open(str(LOCK_FILE), os.O_CREAT | os.O_EXCL | os.O_WRONLY)
        with os.fdopen(fd, "w") as fh:
            fh.write(str(os.getpid()))
        return True
    except FileExistsError:
        try:
            existing_pid = int(LOCK_FILE.read_text().strip() or "0")
            if _ps_alive(existing_pid):
                logger.error("Process already running with PID %s", existing_pid)
                return False
        except Exception:
            pass

        with suppress(Exception):
            LOCK_FILE.unlink()
        return acquire_lock()


def release_lock() -> None:
    try:
        if LOCK_FILE.exists():
            existing_pid = int(LOCK_FILE.read_text().strip() or "0")
            if existing_pid == os.getpid():
                LOCK_FILE.unlink()
    except Exception:
        pass


atexit.register(release_lock)


def _is_video_document(message) -> bool:
    document = getattr(message, "document", None)
    if not document:
        return False
    mime_type = (document.mime_type or "").lower()
    name = (document.file_name or "").lower()
    return mime_type.startswith(ALLOWED_MIME_PREFIXES) or mime_type in ALLOWED_MIME_TYPES or name.endswith(tuple(ALLOWED_VIDEO_SUFFIXES))


def _guess_suffix(filename: str | None, fallback: str = ".mp4") -> str:
    if not filename:
        return fallback
    suffix = Path(filename).suffix.lower()
    return suffix if suffix in ALLOWED_VIDEO_SUFFIXES else fallback


def _validate_video_file(file_name: str | None, mime_type: str | None) -> bool:
    suffix_ok = _guess_suffix(file_name) in ALLOWED_VIDEO_SUFFIXES
    mime = (mime_type or "").lower()
    mime_ok = mime.startswith(ALLOWED_MIME_PREFIXES) or mime in ALLOWED_MIME_TYPES
    return suffix_ok or mime_ok


# ---------------------------------------------------------------------------
# Sync DB wrappers run in a thread to keep the asyncio loop responsive
# ---------------------------------------------------------------------------
async def db_fetch_employee_by_chat(chat_id: str) -> Optional[tuple[int, Optional[int]]]:
    def _work():
        conn = None
        try:
            conn = get_connection()
            cur = conn.cursor()
            row = cur.execute(
                "SELECT id, station_id FROM employees WHERE telegram_chat_id = %s",
                (chat_id,),
            ).fetchone()
            return row
        finally:
            if conn:
                with suppress(Exception):
                    conn.close()

    return await asyncio.to_thread(_work)


async def db_link_employee_chat(employee_id: int, chat_id: str) -> int:
    def _work() -> int:
        conn = None
        try:
            conn = get_connection()
            cur = conn.cursor()
            cur.execute(
                "UPDATE employees SET telegram_chat_id = %s WHERE id = %s",
                (chat_id, employee_id),
            )
            conn.commit()
            return int(cur.rowcount or 0)
        except Exception:
            if conn:
                with suppress(Exception):
                    conn.rollback()
            raise
        finally:
            if conn:
                with suppress(Exception):
                    conn.close()

    return await asyncio.to_thread(_work)


async def db_insert_submission(job: SubmissionJob) -> None:
    def _work() -> None:
        conn = None
        try:
            conn = get_connection()
            cur = conn.cursor()
            cur.execute(
                """
                INSERT INTO submissions (station_id, employee_id, video_path, processed, status)
                VALUES (%s, %s, %s, 0, 'pending')
                """,
                (job.station_id, job.employee_id, job.file_path),
            )
            conn.commit()
        except Exception:
            if conn:
                with suppress(Exception):
                    conn.rollback()
            raise
        finally:
            if conn:
                with suppress(Exception):
                    conn.close()

    await asyncio.to_thread(_work)


async def update_bot_status(status: str, details: str | None = None) -> None:
    payload = {"status": status, "last_update_ts": _now(), "pid": os.getpid()}
    if details:
        payload["details"] = details

    def _work() -> None:
        conn = None
        try:
            conn = get_connection()
            cur = conn.cursor()
            cur.execute(
                """
                INSERT INTO system_settings (key, value)
                VALUES (%s, %s)
                ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value
                """,
                (BOT_STATUS_KEY, _safe_json(payload)),
            )
            conn.commit()
        except Exception as e:
            logger.debug("Could not update bot status: %s", e)
        finally:
            if conn:
                with suppress(Exception):
                    conn.close()

    await asyncio.to_thread(_work)


async def db_record_redis_health(is_online: bool, details: str | None = None) -> None:
    """Records Redis health status to the database."""
    def _work() -> None:
        conn = None
        try:
            conn = get_connection()
            cur = conn.cursor()
            cur.execute(
                """
                INSERT INTO redis_health_logs (is_online, details)
                VALUES (%s, %s)
                """,
                (is_online, details),
            )
            conn.commit()
        except Exception as e:
            logger.debug("Could not record Redis health: %s", e)
        finally:
            if conn:
                with suppress(Exception):
                    conn.close()
    await asyncio.to_thread(_work)

# ---------------------------------------------------------------------------
# Redis queue
# ---------------------------------------------------------------------------
async def get_redis() -> Redis:
    global redis_client
    if Redis is None:
        raise ImportError("The 'redis' library is not installed. Please run: pip install redis")
    if redis_client is None:
        redis_client = Redis.from_url(REDIS_URL, decode_responses=True)
    return redis_client


async def ensure_stream_group(redis: Redis) -> None:
    try:
        await redis.xgroup_create(name=QUEUE_STREAM, groupname=QUEUE_GROUP, id="0", mkstream=True)
    except Exception as e:
        # BUSYGROUP means it already exists.
        if "BUSYGROUP" not in str(e):
            raise


async def enqueue_job(job: SubmissionJob) -> None:
    redis = await get_redis()
    await ensure_stream_group(redis)
    await redis.xadd(QUEUE_STREAM, job.to_redis_mapping(), maxlen=100000, approximate=True)


# ---------------------------------------------------------------------------
# Rate limiting and cleanup
# ---------------------------------------------------------------------------
async def check_rate_limit(chat_id: str) -> bool:
    now = _now()
    async with rate_limit_lock:
        hits = rate_limit_state.setdefault(chat_id, [])
        hits[:] = [ts for ts in hits if now - ts <= RATE_LIMIT_WINDOW_SECONDS]
        if len(hits) >= RATE_LIMIT_MAX_FILES:
            return False
        hits.append(now)
        return True


async def cleanup_old_uploads() -> None:
    while not shutdown_event.is_set():
        try:
            cutoff = _now() - 24 * 3600
            if UPLOADS_DIR.exists():
                for item in UPLOADS_DIR.iterdir():
                    try:
                        if item.is_file() and item.stat().st_mtime < cutoff:
                            item.unlink()
                    except Exception:
                        continue
        except Exception as e:
            logger.warning("Cleanup loop error: %s", e)
        try:
            await asyncio.wait_for(shutdown_event.wait(), timeout=3600)
        except asyncio.TimeoutError:
            pass


async def heartbeat_loop() -> None:
    failure_count = 0
    FAILURE_THRESHOLD = 5

    while not shutdown_event.is_set():
        try:
            if bot_running_event.is_set():
                await update_bot_status("online")
                # Also ping Redis and record its health
                try:
                    redis_client_for_ping = await get_redis()
                    await redis_client_for_ping.ping()
                    await db_record_redis_health(True)
                except Exception as redis_e:
                    logger.warning("Redis ping failed in heartbeat: %s", redis_e)
                    await db_record_redis_health(False, str(redis_e))
                failure_count = 0  # reset on success
        except Exception as e:
            failure_count += 1
            logger.error("Heartbeat error (%s/%s): %s", failure_count, FAILURE_THRESHOLD, e)

            # If too many consecutive failures → mark unhealthy
            if failure_count >= FAILURE_THRESHOLD:
                try:
                    await update_bot_status("unhealthy", f"Heartbeat failed {failure_count} times")
                except Exception:
                    pass

        try:
            await asyncio.wait_for(shutdown_event.wait(), timeout=BOT_HEARTBEAT_INTERVAL)
        except asyncio.TimeoutError:
            pass


# ---------------------------------------------------------------------------
# Telegram handlers
# ---------------------------------------------------------------------------
async def start(update: Update, context: ContextTypes.DEFAULT_TYPE):
    if not update.effective_chat or not update.effective_message:
        return

    chat_id = str(update.effective_chat.id)

    if context.args:
        emp_id_raw = context.args[0]
        if not emp_id_raw.isdigit():
            await update.effective_message.reply_text("❌ Invalid registration link. Please request a new invite.")
            return

        emp_id = int(emp_id_raw)
        try:
            rowcount = await db_link_employee_chat(emp_id, chat_id)
            if rowcount > 0:
                await update.effective_message.reply_text(
                    f"✅ Registration successful. Employee ID {emp_id} is now linked to this chat."
                )
            else:
                await update.effective_message.reply_text("❌ Employee ID not found in database.")
        except Exception as e:
            logger.exception("Error linking Telegram chat %s to employee %s: %s", chat_id, emp_id, e)
            await update.effective_message.reply_text("⚠️ Database error while linking account. Please try again.")
    else:
        await update.effective_message.reply_text(
            "Welcome. Please use the link from your registration email to link your account."
        )


async def handle_media(update: Update, context: ContextTypes.DEFAULT_TYPE):
    message = update.effective_message
    if not message or not update.effective_chat:
        return

    chat_id = str(update.effective_chat.id)

    if not await check_rate_limit(chat_id):
        await message.reply_text("⚠️ You are sending files too quickly. Please wait a moment and try again.")
        return

    try:
        emp = await db_fetch_employee_by_chat(chat_id)
    except Exception as e:
        logger.exception("Error fetching employee link for chat %s: %s", chat_id, e)
        await message.reply_text("⚠️ Could not verify your account link. Please try again shortly.")
        return

    if not emp:
        await message.reply_text("❌ Your Telegram is not linked. Please use the link from your email.")
        return

    emp_id, station_id = emp
    if not station_id:
        await message.reply_text("❌ Your profile has no station assigned yet. Please contact an administrator.")
        return

    if message.video:
        media = message.video
        original_name = getattr(media, "file_name", None) or f"video_{message.message_id}.mp4"
    elif _is_video_document(message):
        media = message.document
        original_name = getattr(media, "file_name", None) or f"document_{message.message_id}.mp4"
    else:
        await message.reply_text("❌ Please send a video file (mp4/mov/mkv/webm) to queue it for AI analysis.")
        return

    if not _validate_video_file(getattr(media, "file_name", None), getattr(media, "mime_type", None)):
        await message.reply_text("❌ Unsupported file type. Please send a video file (mp4/mov/mkv/webm).")
        return

    media_size = int(getattr(media, "file_size", 0) or 0)
    if media_size > MAX_VIDEO_SIZE_MB * 1024 * 1024:
        await message.reply_text(f"❌ File is too large. Max allowed size is {MAX_VIDEO_SIZE_MB} MB.")
        return

    UPLOADS_DIR.mkdir(parents=True, exist_ok=True)
    suffix = _guess_suffix(getattr(media, "file_name", None), ".mp4")
    safe_name = f"vid_{chat_id}_{message.message_id}_{uuid.uuid4().hex}{suffix}"
    file_path = UPLOADS_DIR / Path(safe_name).name

    try:
        tg_file = await media.get_file()
        await tg_file.download_to_drive(custom_path=str(file_path))
    except Exception as e:
        logger.exception("Failed to download media for chat %s: %s", chat_id, e)
        with suppress(Exception):
            if file_path.exists():
                file_path.unlink()
        await message.reply_text("⚠️ Could not download your video. Please try sending it again.")
        return

    job = SubmissionJob(
        job_id=uuid.uuid4().hex,
        chat_id=chat_id,
        employee_id=emp_id,
        station_id=station_id,
        file_path=str(file_path),
        original_file_name=str(getattr(media, "file_name", "") or ""),
        size_bytes=media_size,
        created_ts=_now(),
    )

    try:
        # Insert the submission record first, then enqueue the processing job.
        await db_insert_submission(job)
        await enqueue_job(job)
        logger.info("Queued job %s for station %s and employee %s", job.job_id, station_id, emp_id)
    except Exception as e:
        logger.exception("Error queuing submission %s: %s", job.job_id, e)
        with suppress(Exception):
            if file_path.exists():
                file_path.unlink()
        await message.reply_text("⚠️ I received the file, but could not queue it for analysis.")
        return

    await message.reply_text("✅ Video received and queued for AI analysis. You will see the results in the Dashboard shortly.")


async def error_handler(update: object, context: ContextTypes.DEFAULT_TYPE):
    logger.exception("Unhandled bot error: %s", context.error)


# ---------------------------------------------------------------------------
# Worker process
# ---------------------------------------------------------------------------
async def update_job_status(job_id: str, status: str) -> None:
    def _work():
        conn = None
        try:
            conn = get_connection()
            cur = conn.cursor()
            cur.execute("UPDATE submissions SET status=%s WHERE video_path=%s", (status, job_id))
            conn.commit()
        finally:
            if conn:
                with suppress(Exception):
                    conn.close()
    await asyncio.to_thread(_work)


async def process_job(redis: Redis, stream_id: str, job: SubmissionJob) -> None:
    await update_job_status(job.file_path, "processing")

    def _simulate_or_run_heavy_task() -> None:
        return None

    try:
        await asyncio.to_thread(_simulate_or_run_heavy_task)
        await update_job_status(job.file_path, "done")
        logger.info("Processed job %s (stream id %s)", job.job_id, stream_id)
    except Exception as e:
        await update_job_status(job.file_path, "failed")
        raise


async def worker_loop() -> None:
    redis = await get_redis()
    await ensure_stream_group(redis)
    consumer_name = os.getenv("QUEUE_CONSUMER") or f"{socket.gethostname()}-{os.getpid()}"

    while not shutdown_event.is_set():
        try:
            entries = await redis.xreadgroup(
                groupname=QUEUE_GROUP,
                consumername=consumer_name,
                streams={QUEUE_STREAM: ">"},
                count=10,
                block=5000,
            )

            if not entries:
                continue

            for _stream_name, messages in entries:
                for stream_id, mapping in messages:
                    try:
                        job = SubmissionJob.from_redis_mapping(mapping)
                        await process_job(redis, stream_id, job)
                        await redis.xack(QUEUE_STREAM, QUEUE_GROUP, stream_id)
                    except Exception as e:
                        logger.exception("Worker failed for stream id %s: %s", stream_id, e)
                        # Leave unacked for retry / inspection. You can add DLQ handling here.
        except asyncio.CancelledError:
            break
        except Exception as e:
            logger.error("Worker loop error: %s", e)
            try:
                await asyncio.wait_for(shutdown_event.wait(), timeout=5)
            except asyncio.TimeoutError:
                pass


# ---------------------------------------------------------------------------
# Bot lifecycle
# ---------------------------------------------------------------------------
async def build_application() -> Application:
    if not TOKEN:
        raise RuntimeError("TELEGRAM_BOT_TOKEN not found in environment")

    app = ApplicationBuilder().token(TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    media_filter = (
        filters.VIDEO
        | filters.Document.VIDEO
        | filters.Document.MimeType("video/mp4")
        | filters.Document.MimeType("video/quicktime")
        | filters.Document.MimeType("video/webm")
        | filters.Document.MimeType("video/x-matroska")
    )
    app.add_handler(MessageHandler(media_filter, handle_media))
    app.add_error_handler(error_handler)
    return app


async def run_bot_once() -> None:
    if not TOKEN:
        logger.error("TELEGRAM_BOT_TOKEN not found in .env")
        await update_bot_status("offline", "missing TELEGRAM_BOT_TOKEN")
        return

    app = await build_application()
    bot_running_event.set()
    await update_bot_status("starting")

    await app.initialize()
    await app.start()
    await app.updater.start_polling(drop_pending_updates=True)
    logger.info("Telegram bot is running.")

    try:
        await shutdown_event.wait()
    finally:
        bot_running_event.clear()
        with suppress(Exception):
            await app.updater.stop()
        with suppress(Exception):
            await app.stop()
        with suppress(Exception):
            await app.shutdown()
        await update_bot_status("stopped")


async def run_bot_with_retry() -> None:
    retry_delay = max(1, RETRY_BASE_SECONDS)

    while not shutdown_event.is_set():
        try:
            await run_bot_once()
            retry_delay = RETRY_BASE_SECONDS

            if shutdown_event.is_set():
                break

            logger.warning("Bot stopped unexpectedly. Restarting in %s sec...", retry_delay)

        except (NetworkError, TimedOut, RetryAfter) as e:
            logger.error("Network error: %s", e)

        except TelegramError as e:
            logger.error("Telegram API error: %s", e)

        except Exception as e:
            logger.exception("Bot crashed: %s", e)

        await asyncio.sleep(retry_delay)
        retry_delay = min(RETRY_MAX_SECONDS, retry_delay * 2)


async def run_both() -> None:
    tasks = []
    if BOT_MODE in {"bot", "both"}:
        tasks.append(asyncio.create_task(run_bot_with_retry(), name="telegram-bot"))
    if BOT_MODE in {"worker", "both"}:
        tasks.append(asyncio.create_task(worker_loop(), name="queue-worker"))
    tasks.append(asyncio.create_task(heartbeat_loop(), name="heartbeat"))
    tasks.append(asyncio.create_task(cleanup_old_uploads(), name="cleanup"))

    try:
        await asyncio.gather(*tasks)
    finally:
        for t in tasks:
            t.cancel()
        with suppress(Exception):
            await asyncio.gather(*tasks, return_exceptions=True)


def _install_signal_handlers(loop: asyncio.AbstractEventLoop) -> None:
    def _stop(*_: Any) -> None:
        shutdown_event.set()

    for sig_name in ("SIGINT", "SIGTERM"):
        sig = getattr(signal, sig_name, None)
        if sig is None:
            continue
        with suppress(NotImplementedError, RuntimeError):
            loop.add_signal_handler(sig, _stop)


async def main() -> None:
    load_dotenv()
    UPLOADS_DIR.mkdir(parents=True, exist_ok=True)

    if Redis is None:
        logger.error("FATAL: The 'redis' library is missing. Background workers cannot start.")
        await update_bot_status("error", "Library Missing: redis")
        return

    if not acquire_lock():
        logger.error("Lock file could not be acquired; another instance is active.")
        return

    loop = asyncio.get_running_loop()
    _install_signal_handlers(loop)

    try:
        if BOT_MODE == "bot":
            tasks = [
                asyncio.create_task(run_bot_with_retry(), name="telegram-bot"),
                asyncio.create_task(heartbeat_loop(), name="heartbeat"),
                asyncio.create_task(cleanup_old_uploads(), name="cleanup"),
            ]
            await asyncio.gather(*tasks)
        elif BOT_MODE == "worker":
            tasks = [asyncio.create_task(worker_loop(), name="queue-worker")]
            await asyncio.gather(*tasks)
        elif BOT_MODE == "both":
            await run_both()
        else:
            raise ValueError(f"Unsupported BOT_MODE={BOT_MODE!r}. Use bot, worker, or both.")
    except KeyboardInterrupt:
        shutdown_event.set()
    except Exception as e:
        logger.exception("Fatal error: %s", e)
        await update_bot_status("error", str(e))
        raise
    finally:
        shutdown_event.set()
        with suppress(Exception):
            if redis_client is not None:
                await redis_client.close()
                await redis_client.connection_pool.disconnect()
        with suppress(Exception):
            await update_bot_status("stopped")
        release_lock()


if __name__ == "__main__":
    asyncio.run(main())
