"""convert serial to identity

Revision ID: xxxx_convert_serial
Revises: <previous_revision_id>
Create Date: 2024-05-20 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# List of tables that were created with SERIAL in ensure_schema
TABLES_TO_CONVERT = [
    "regions", "stations", "users", "activity_logs", "submissions",
    "ai_alerts", "redis_health_logs",
    "ai_inference_latency", "worker_health_logs", "slow_query_logs",
    "ai_jobs", "ai_reports"
]

def upgrade():
    for table in TABLES_TO_CONVERT:
        # 1. Drop the DEFAULT constraint (this unlinks the SERIAL sequence)
        op.execute(f"ALTER TABLE {table} ALTER COLUMN id DROP DEFAULT")

        # 2. Change the column to IDENTITY
        op.execute(f"ALTER TABLE {table} ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY")

        # 3. Synchronize the new identity sequence with the existing data
        # We use a subquery to find the current max ID and restart the identity sequence from there.
        op.execute(sa.text(f"""
            DO $$
            DECLARE
                max_id integer;
            BEGIN
                EXECUTE 'SELECT COALESCE(MAX(id), 0) + 1 FROM {table}' INTO max_id;
                EXECUTE 'ALTER TABLE {table} ALTER COLUMN id RESTART WITH ' || max_id;
            END $$;
        """))

        # 4. Cleanup: Drop the old sequence if it still exists and isn't linked
        # SERIAL created sequences usually named {table}_id_seq
        op.execute(f"DROP SEQUENCE IF EXISTS {table}_id_seq")

def downgrade():
    for table in TABLES_TO_CONVERT:
        # 1. Remove the IDENTITY property
        op.execute(f"ALTER TABLE {table} ALTER COLUMN id DROP IDENTITY IF EXISTS")

        # 2. Re-create the sequence manually
        op.execute(f"CREATE SEQUENCE IF NOT EXISTS {table}_id_seq")

        # 3. Set the column default back to the sequence
        op.execute(f"ALTER TABLE {table} ALTER COLUMN id SET DEFAULT nextval('{table}_id_seq')")

        # 4. Sync the sequence
        op.execute(sa.text(f"""
            DO $$
            DECLARE
                max_id integer;
            BEGIN
                EXECUTE 'SELECT COALESCE(MAX(id), 0) + 1 FROM {table}' INTO max_id;
                EXECUTE 'SELECT setval(''{table}_id_seq'', ' || max_id || ', false)';
            END $$;
        """))
